In [2]:
import numpy as np

x=np.array([1,2,3])
print(x.ndim)
print(x.shape)

y=np.array([[1,2,3],[4,5,6]])
print(y.ndim)
print(y.shape)


1
(3,)
2
(2, 3)


ndim用于输出维度
shape用于输出形状，但是对于1维会输出（列数，）

矩阵元素的运算
1.+ *，都是对应位置的元素相加相乘
2.广播(地位元素扩展复制)
3.向量内积和矩阵乘积(dot)
4.注意矩阵形状检查

In [3]:
Z=np.array([[5,7,9],[4,7,3]])
W1=Z+y
W2=Z*y
print(W1)
print(W2)

A=Z*10
print(A)
b = np.array([10, 20,30])
B=b*Z
print(B)

[[ 6  9 12]
 [ 8 12  9]]
[[ 5 14 27]
 [16 35 18]]


In [4]:
a=np.array([1,2,3])
b=np.array([2,3,4])
c=np.dot(a,b)
print(c)

a=np.array([[1,2,3],[4,5,6]])
b=np.array([[2,3,4],[1,2,4],[6,5,7]])
c=np.dot(a,b)
print(c)



20
[[22 22 33]
 [49 52 78]]
